name: gh-pages-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'tsconfig.json'
      - 'package.json'
      - 'src/*/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn ci
    - name: Build
      run: |
        yarn build
        mv .\build\* buildCI
    - name: Commit build
      run: |
        git config --global user.name 'Cody Duong'
        git config --global user.email 'codyduong@users.noreply.github.com'
        git fetch --all
        git add .
        git stash
        git checkout -b "gh-pages" "origin/gh-pages"
        git stash pop
        rm -r static
        cp .\buildCI\* .
        cp -r .\buildCI\css static
        cp -r .\buildCI\js static
        cp -r .\buildCI\media static
        rm -r buildCI
        git add .
        git commit -am "Automated Build"
        git push
