name: gh-pages-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'tsconfig.json'
      - 'package.json'
      - 'src/*/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn ci
    - name: Build
      run: |
        yarn build
        cp -r build buildCI
      env:
        REACT_APP_GOOGLE_MAPS_API_KEY:  ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
        REACT_APP_API_KEY:  ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_AUTH_DOMAIN:  ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID:  ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET:  ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID:  ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID:  ${{ secrets.REACT_APP_APP_ID }}
        REACT_APP_MEASUREMENT_ID:  ${{ secrets.REACT_APP_MEASUREMENT_ID }}
        REACT_APP_CLOUD_URL: ${{ secrets.REACT_APP_CLOUD_URL }}
    - name: Commit build
      run: |
        git config --global user.name 'Cody Duong'
        git config --global user.email 'codyduong@users.noreply.github.com'
        git fetch --all
        git add .
        git stash
        git checkout -b "gh-pages" "origin/gh-pages"
        git stash pop
        rm -r static
        rm -f asset-manifest.json
        rm -f favicon.ico
        rm -f index.html
        rm -f manifest.json
        rm -f robots.txt
        cp -R ./buildCI/* ./
        rm -r buildCI
        git add .
        git commit -am "Automated Build"
        git push
